<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.e3eUotr' shared service.

return $this->privates['.service_locator.e3eUotr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\ArticleController::deleteVerif' => ['privates', '.service_locator.VpK.6BC', 'get_ServiceLocator_VpK_6BCService.php', true],
    'App\\Controller\\ArticleController::deleterArticle' => ['privates', '.service_locator.VpK.6BC', 'get_ServiceLocator_VpK_6BCService.php', true],
    'App\\Controller\\ArticleController::indexAction' => ['privates', '.service_locator.VpK.6BC', 'get_ServiceLocator_VpK_6BCService.php', true],
    'App\\Controller\\ArticleController::updateAction' => ['privates', '.service_locator.VpK.6BC', 'get_ServiceLocator_VpK_6BCService.php', true],
    'App\\Controller\\TestController::testerTwig' => ['privates', '.service_locator.3hxx.mU', 'get_ServiceLocator_3hxx_MUService.php', true],
    'App\\Controller\\UserController::login' => ['privates', '.service_locator.FAee79i', 'get_ServiceLocator_FAee79iService.php', true],
    'App\\Controller\\ArticleController:deleteVerif' => ['privates', '.service_locator.VpK.6BC', 'get_ServiceLocator_VpK_6BCService.php', true],
    'App\\Controller\\ArticleController:deleterArticle' => ['privates', '.service_locator.VpK.6BC', 'get_ServiceLocator_VpK_6BCService.php', true],
    'App\\Controller\\ArticleController:indexAction' => ['privates', '.service_locator.VpK.6BC', 'get_ServiceLocator_VpK_6BCService.php', true],
    'App\\Controller\\ArticleController:updateAction' => ['privates', '.service_locator.VpK.6BC', 'get_ServiceLocator_VpK_6BCService.php', true],
    'App\\Controller\\TestController:testerTwig' => ['privates', '.service_locator.3hxx.mU', 'get_ServiceLocator_3hxx_MUService.php', true],
    'App\\Controller\\UserController:login' => ['privates', '.service_locator.FAee79i', 'get_ServiceLocator_FAee79iService.php', true],
], [
    'App\\Controller\\ArticleController::deleteVerif' => '?',
    'App\\Controller\\ArticleController::deleterArticle' => '?',
    'App\\Controller\\ArticleController::indexAction' => '?',
    'App\\Controller\\ArticleController::updateAction' => '?',
    'App\\Controller\\TestController::testerTwig' => '?',
    'App\\Controller\\UserController::login' => '?',
    'App\\Controller\\ArticleController:deleteVerif' => '?',
    'App\\Controller\\ArticleController:deleterArticle' => '?',
    'App\\Controller\\ArticleController:indexAction' => '?',
    'App\\Controller\\ArticleController:updateAction' => '?',
    'App\\Controller\\TestController:testerTwig' => '?',
    'App\\Controller\\UserController:login' => '?',
]);
