<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerT2TA1fx\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerT2TA1fx/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerT2TA1fx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerT2TA1fx\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerT2TA1fx\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'T2TA1fx',
    'container.build_id' => 'b0cbe6c1',
    'container.build_time' => 1571057080,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerT2TA1fx');
